name: Install spcli-ui

on:
  push:
    branches:    
      - 'main'
      - 'feature/**'
  pull_request:
    types: [opened, reopened,edited]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        editable: '.'
    #- run: sp -v # <-- only one value is allowed